version: "3.5"

services:
  db:
    image: postgres:10.1-alpine
    container_name: sketch-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sketch
      POSTGRES_PASSWORD: sketch
      POSTGRES_DB: sketch

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sketch-app
    env_file:
    - .env
    ports:
    - "${ASPNETCORE_SOCKET_BIND_PORT}:${ASPNETCORE_SOCKET_BIND_PORT}"
    depends_on:
      - db
      - elk
    command:
      [
      "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
      "./scripts/wait-for-it.sh",
        "elk:9200",
        "-t",
        "120",
        "--",
        "./scripts/start-from-compose.sh",
      ]

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sketch-tests
    env_file:
    - .env
    volumes:
    - .:/app
    depends_on:
      - db
    command:
      [
      "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "dotnet",
        "test"
      ]

  # ELK stack
  elk:
    container_name: sketch-elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      MAX_MAP_COUNT: 262144
      ES_JAVA_OPTS: -Xms512m -Xmx512m